# 開発環境構成用docker-compose
#
name: yt-smtp-catcher-development
services:
    # メインのSMTPサーバーをデバッグ実行する
    yt-smtp-catcher:
        build:
            context: ./
            dockerfile: ./docker/main/Dockerfile
        volumes:
            - type: bind 
              source: ${WORK_DIR?err}/
              target: /workspace/
            - type: volume
              source: app_data
              target: /workspace/data
        ports:
            - target: 8000
              published: 8000
              protocol: tcp
              mode: host
        environment:
            LANG: ja_JP.UTF-8
            DEBUG: 1
        restart: "no"

    # E2Eテスト用のSeleniumサーバー
    selenium-chrome:
        image: selenium/standalone-chrome:latest
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"
        environment:
            - SE_NODE_OVERRIDE_MAX_SESSIONS=true
            - SE_NODE_MAX_SESSIONS=5

volumes:
    app_data: