# DevContainer構成用docker-compose
#
# Docker outside of Docker(DooD)を利用しているので、
# Windowsで利用する場合は以下の環境変数を設定する必要がある。
# COMPOSE_CONVERT_WINDOWS_PATHS=1
version: '3.6'

services:
    # 開発作業用コンテナ
    devcontainer:
        build:
            context: ../
            dockerfile: ./.devcontainer/Dockerfile
        volumes:
            - type: bind 
              source: ../
              target: /workspace/
            - type: volume
              source: app_data
              target: /workspace/data
            # Docker Outside of Dockerの設定
            # この機能をWindowsで動かすためには上記の環境変数が必要。
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
        environment:
            LANG: ja_JP.UTF-8

volumes:
    app_data: